short_description: >
 Test power management (PM-QA).

description: |
 Test power management (PM-QA). Currently, the test runs cpufreq, cpuidle,
 cpuhotplug, thermal and cputopology by default and individual test can be run
 by setting TESTS parameter in test job definition too.

homepage: https://git.linaro.org/power/pm-qa.git

parameters:
 test:

results:
